### PR TITLE
fix(search-result) scrolling visibility

### PR DESCRIPTION
**Pull request by geromegrignon**
changes scrolling visibility on mat-card-content as overflow-x was visible by default.
It's only displayed when needed now.

### CODE REVIEW

**Comment by manekinekko** [comment]
Hi @geromegrignon thanks for your PR. Could you, however, remove the package-lock.json from the changes?

**Comment by geromegrignon** [comment]
Hi, i removed the file.

**Comment by geromegrignon** [comment]
My fault too : starting contributing, i need to be more careful.
How can i fix it?

**Comment by manekinekko** [comment]
No big deal 😇

You can git add the package-lock.json file back and push it. I'll take care of that.

**Pull request merged**
